### ISSUE TITLE
[question] need a API to get the progress of component installation

### ISSUE THREAD

**Issue by xiaoyaodingchunqiu** [awslabs/aws-iot-greengrass-accelerators#24]
Is there any API to get the progress of component installation? Hope that customers can see the progress of the deployment in time Thanks!

**Comment by gadams999** [comment]
Hello,

This is more a general Greengrass question and not one related to the accelerators. There was a similar (or same) question asked [here on re:Post](https://repost.aws/questions/QUZU4IS2q1Rdyp4GNBTJ3huw) for you to follow.
