### ISSUE TITLE
Boto3 dependency missing in Cloud9 instance

### ISSUE THREAD

**Issue by jrichrd** [awslabs/aws-iot-greengrass-accelerators#4]
Hi, I am setting up the 'AWS IoT Greengrass Stream Manager accelerator' on a fresh Cloud9 instance as described in the setup instructions and hit an issue in Step #3 as boto3 was not available by default on a fresh Cloud9 instance running Amazon Linux ->

```
python3 deploy_resources.py -p default

Traceback (most recent call last):
  File "deploy_resources.py", line 6, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

A simple **pip3 install boto3** resolved the issue but wanted to highlight this so that the pre-requisite steps can be updated to include this dependency.

**Comment by gadams999** [comment]
Doc's updated for Cloud9 script adding:

```
pip3 install --user boto3
```

**Comment by jaimedantas** [comment]
The only thing that worked for me was:
`sudo -H -u ggc_user python3 -m pip install boto3`
