### ISSUE TITLE
Cloud9 - Disk space error

### ISSUE THREAD

**Issue by jrichrd** [awslabs/aws-iot-greengrass-accelerators#5]
Hi, When working through the install steps for the 'AWS IoT Greengrass Stream Manager' accelerator using a Cloud 9 setup I experienced an issue on Step #3 at: when executing the **docker-compose build** command related to insufficient disk space.

```
Transaction check error:
  installing package containerd-1.3.2-1.amzn2.x86_64 needs 90MB on the / filesystem
  installing package libcgroup-0.41-21.amzn2.x86_64 needs 90MB on the / filesystem
  installing package pigz-2.3.4-1.amzn2.0.1.x86_64 needs 90MB on the / filesystem
  installing package xfsprogs-4.5.0-18.amzn2.0.1.x86_64 needs 95MB on the / filesystem
  installing package docker-19.03.6ce-4.amzn2.x86_64 needs 264MB on the / filesystem
  installing package setup-2.8.71-10.amzn2.0.1.noarch needs 265MB on the / filesystem

Error Summary
-------------
Disk Requirements:
  At least 265MB more space needed on the / filesystem.
```

To resolve the issue I was able to resize the EBS volume attached to the Cloud 9 instance to 15GB by following the steps outlined in the user guide @ https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html. 

It appears that a 10GB EBS volume is created by default when creating a new Cloud 9 environment regardless of the 'Instance Type' that is selected e.g. t3.small, m5.large etc. I wasn't able to find an way to increase the default EBS Volume size when creating a new Cloud 9 instance so I would presume anyone who runs this sample project would need to increase the volume unless there is a way to remove some dependencies to reduce the install req footprint.

**Comment by gadams999** [comment]
Thanks for the feedback! The documentation has been update to refer to the process for increasing the Cloud9. To be more prescriptive, we now call out:

1. t3.small as instance type
1. Change to Amazon Linux 2
1. Process to increase EBS volume
